// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0X9915XtISwISe69lWJwnYuyizxtg--k',
    appId: '1:267636346874:web:994764d750809630609e43',
    messagingSenderId: '267636346874',
    projectId: 'v5charactersheet',
    authDomain: 'v5charactersheet.firebaseapp.com',
    databaseURL: 'https://v5charactersheet.firebaseio.com',
    storageBucket: 'v5charactersheet.appspot.com',
    measurementId: 'G-GETJ8ELL11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqcUHGftDSesr3z14Q0oMAPK5OCumHiaA',
    appId: '1:267636346874:android:577cf8fa59298b04609e43',
    messagingSenderId: '267636346874',
    projectId: 'v5charactersheet',
    databaseURL: 'https://v5charactersheet.firebaseio.com',
    storageBucket: 'v5charactersheet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOqr3m6-89gnJI_hZYatKvM7jjaSXf1Hg',
    appId: '1:267636346874:ios:48708972f57e96af609e43',
    messagingSenderId: '267636346874',
    projectId: 'v5charactersheet',
    databaseURL: 'https://v5charactersheet.firebaseio.com',
    storageBucket: 'v5charactersheet.appspot.com',
    androidClientId: '267636346874-84pghftjmasfhag1naa98v75v8fkv6cc.apps.googleusercontent.com',
    iosClientId: '267636346874-vvjlltt64jm3s9uu7i4mkg4ftmi24jde.apps.googleusercontent.com',
    iosBundleId: 'com.dragonsden.v5charactersheet',
  );
}
